var card1 = document.getElementById("card1")

var imgshoes = document.createElement("img")
var h3 = document.createElement("h3")
var peraH = document.createElement("p")
var h6 = document.createElement("h6")
var star = document.createElement("ul")
var button = document.createElement("button")

var shoesheading = document.createTextNode("Shoes")
var pera = document.createTextNode("A shoe is an item of footwear intended to protect and comfort the human foot")
var shoes_RS = document.createTextNode("RS 5,000")
var star_in1 = document.createElement("li")
var star_in2 = document.createElement("li")
var star_in3 = document.createElement("li")
var star_in4 = document.createElement("li")
var star_in5 = document.createElement("li")
var buttontext = document.createTextNode("Buy Now")

star_in1.setAttribute("class","fa-solid fa-star ok fa")
star_in2.setAttribute("class","fa-solid fa-star ok fa")
star_in3.setAttribute("class","fa-solid fa-star ok fa")
star_in4.setAttribute("class","fa-solid fa-star ok fa")
star_in5.setAttribute("class","fa-solid fa-star ok")
card1.setAttribute("class","sabCard")
h3.setAttribute("class","h3")
imgshoes.setAttribute("class","image")
peraH.setAttribute("class","peragrave")
h6.setAttribute("class","h6")
star.setAttribute("class","ul")
button.setAttribute("class","button")


imgshoes.setAttribute("src","./image/images__3_-removebg-preview.png")
h3.appendChild(shoesheading)
peraH.appendChild(pera)
h6.appendChild(shoes_RS)
star.appendChild(star_in1)
star.appendChild(star_in2)
star.appendChild(star_in3)
star.appendChild(star_in4)
star.appendChild(star_in5)
button.appendChild(buttontext)

card1.appendChild(imgshoes)
card1.appendChild(h3)
card1.appendChild(peraH)
card1.appendChild(h6)
card1.appendChild(star)
card1.appendChild(button)






var card2 = document.getElementById("card2")

var imgshoes = document.createElement("img")
var h3 = document.createElement("h3")
var peraH = document.createElement("p")
var h6 = document.createElement("h6")
var star = document.createElement("ul")
var button = document.createElement("button")

var shoesheading = document.createTextNode("Shoes")
var pera = document.createTextNode("A shoe is an item of footwear intended to protect and comfort the human foot")
var shoes_RS = document.createTextNode("RS 5,000")
var star_in1 = document.createElement("li")
var star_in2 = document.createElement("li")
var star_in3 = document.createElement("li")
var star_in4 = document.createElement("li")
var star_in5 = document.createElement("li")
var buttontext = document.createTextNode("Buy Now")

star_in1.setAttribute("class","fa-solid fa-star ok fa")
star_in2.setAttribute("class","fa-solid fa-star ok fa")
star_in3.setAttribute("class","fa-solid fa-star ok fa")
star_in4.setAttribute("class","fa-solid fa-star ok")
star_in5.setAttribute("class","fa-solid fa-star ok")
card2.setAttribute("class","sabCard")


imgshoes.setAttribute("src","./image/images__3_-removebg-preview.png")
h3.appendChild(shoesheading)
peraH.appendChild(pera)
h6.appendChild(shoes_RS)
star.appendChild(star_in1)
star.appendChild(star_in2)
star.appendChild(star_in3)
star.appendChild(star_in4)
star.appendChild(star_in5)
button.appendChild(buttontext)

card2.appendChild(imgshoes)
card2.appendChild(h3)
card2.appendChild(peraH)
card2.appendChild(h6)
card2.appendChild(star)
card2.appendChild(button)





var card3 = document.getElementById("card3")

var imgshoes = document.createElement("img")
var h3 = document.createElement("h3")
var peraH = document.createElement("p")
var h6 = document.createElement("h6")
var star = document.createElement("ul")
var button = document.createElement("button")

var shoesheading = document.createTextNode("Shoes")
var pera = document.createTextNode("A shoe is an item of footwear intended to protect and comfort the human foot")
var shoes_RS = document.createTextNode("RS 5,000")
var star_in1 = document.createElement("li")
var star_in2 = document.createElement("li")
var star_in3 = document.createElement("li")
var star_in4 = document.createElement("li")
var star_in5 = document.createElement("li")
var buttontext = document.createTextNode("Buy Now")

star_in1.setAttribute("class","fa-solid fa-star ok fa")
star_in2.setAttribute("class","fa-solid fa-star ok fa")
star_in3.setAttribute("class","fa-solid fa-star ok fa")
star_in4.setAttribute("class","fa-solid fa-star ok fa")
star_in5.setAttribute("class","fa-solid fa-star ok fa")
card3.setAttribute("class","sabCard")

imgshoes.setAttribute("src","./image/images__3_-removebg-preview.png")
h3.appendChild(shoesheading)
peraH.appendChild(pera)
h6.appendChild(shoes_RS)
star.appendChild(star_in1)
star.appendChild(star_in2)
star.appendChild(star_in3)
star.appendChild(star_in4)
star.appendChild(star_in5)
button.appendChild(buttontext)

card3.appendChild(imgshoes)
card3.appendChild(h3)
card3.appendChild(peraH)
card3.appendChild(h6)
card3.appendChild(star)
card3.appendChild(button)



var card4 = document.getElementById("card4")

var imgshoes = document.createElement("img")
var h3 = document.createElement("h3")
var peraH = document.createElement("p")
var h6 = document.createElement("h6")
var star = document.createElement("ul")
var button = document.createElement("button")

var shoesheading = document.createTextNode("Shoes")
var pera = document.createTextNode("A shoe is an item of footwear intended to protect and comfort the human foot")
var shoes_RS = document.createTextNode("RS 5,000")
var star_in1 = document.createElement("li")
var star_in2 = document.createElement("li")
var star_in3 = document.createElement("li")
var star_in4 = document.createElement("li")
var star_in5 = document.createElement("li")
var buttontext = document.createTextNode("Buy Now")

star_in1.setAttribute("class","fa-solid fa-star ok fa")
star_in2.setAttribute("class","fa-solid fa-star ok fa")
star_in3.setAttribute("class","fa-solid fa-star ok fa")
star_in4.setAttribute("class","fa-solid fa-star ok fa")
star_in5.setAttribute("class","fa-solid fa-star ok")
card4.setAttribute("class","sabCard")

imgshoes.setAttribute("src","./image/images__3_-removebg-preview.png")
h3.appendChild(shoesheading)
peraH.appendChild(pera)
h6.appendChild(shoes_RS)
star.appendChild(star_in1)
star.appendChild(star_in2)
star.appendChild(star_in3)
star.appendChild(star_in4)
star.appendChild(star_in5)
button.appendChild(buttontext)

card4.appendChild(imgshoes)
card4.appendChild(h3)
card4.appendChild(peraH)
card4.appendChild(h6)
card4.appendChild(star)
card4.appendChild(button)